### ISSUE TITLE
kubectl explain should explain the kapp controller defined resources

### ISSUE THREAD

**Issue by renuy** [carvel-dev/kapp-controller#481] opened 2022-01-19 04:43 UTC
**Describe the problem/challenge you have**
For the following commands 
kubectl explain Package
kubectl explain PackageMetadata
kubectl explain PackageInstall
kubectl explain PackageRepository

I dont get any description or spec.

example:
```code
kubectl explain Package
KIND:     Package
VERSION:  data.packaging.carvel.dev/v1alpha1

DESCRIPTION:
     <empty>

FIELDS:
   apiVersion	<string>
     APIVersion defines the versioned schema of this representation of an
     object. Servers should convert recognized schemas to the latest internal
     value, and may reject unrecognized values. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources

   kind	<string>
     Kind is a string value representing the REST resource this object
     represents. Servers may infer this from the endpoint the client submits
     requests to. Cannot be updated. In CamelCase. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds

   metadata	<Object>
     Standard object metadata; More info:
     https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata.

   spec	<Object> -required-
```

**Describe the solution you'd like**
It would be good to have these published these in the cluster.

**Anything else you would like to add:**
Should this be also available for
InternalPackageMetadata and InternalPackage

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by benmoss** [comment] 2022-01-19 14:40
Dup of #49?

**Comment by danielhelfand** [comment] 2022-01-19 15:34
This is a duplicate of #49 and there is more detail provided in that issue. This is good signal we should move up in our backlog though. I'll close this for now, but we'll try and have this prioritized soon.

**Closed as completed by danielhelfand** 2022-01-19 15:34 UTC
Labels: enhancement
