### ISSUE TITLE
[template] support helm v3

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/kapp-controller#53] opened 2020-12-01 01:27 UTC
consider supporting include CRDs flag. still want to support helm v2. should we make this consistent with how vendir selects helm version?

**Comment by absoludity** [comment] 2021-02-09 03:11
Duplicate of #33 ? (appears to be the same request - support for `--include-crds`

**Comment by migmartri** [comment] 2021-04-01 20:41
Hi!

> still want to support helm v2.

Helm V2 maintenance support [ended on November 2020](https://helm.sh/blog/helm-v2-deprecation-timeline/) and the Helm community seems (based on limited empirical evidence) to have moved on to V3. Do we really need to support Helm V2 templating? Maybe not maintaining V2 could simplify the upgrade?

Thanks!
Miguel

**Comment by migmartri** [comment] 2021-04-05 18:54
I am happy to work on this if you are ok with it. Feel free to assign this issue to me so we do not duplicate efforts!

**Comment by migmartri** [comment] 2021-04-06 19:04
Hi,

Assuming that the scope of this effort is just to be able to render templates for charts.apiVersion=v2, only compatible with Helm v3+, while maintaining either full, best effort or no support for current charts.apiVersion=v1 ([not maintained upstream anymore](https://helm.sh/blog/helm-v2-deprecation-timeline/)).

I can see two possible ways to tackle the problem, always following the same pattern laid down in this tool of relying on third party binaries (not libraries), in this case, the `helm` binary for templating.

**a) Upgrade the `helm` binary to 3.x**

Helm V3 client has support for charts v2 templating but also v1 fallback for old charts (v1 chart spec). This fallback support is not 1-1, since for example Helm v3 will fail to render if the template contains things like `if semverCompare ">=2.14.0" $.Capabilities.TillerVersion.SemVer` but the current helm v2 binary will render it accordingly.

The main change is that helm V3 template command does not render CRDs by default anymore, in order to do it we will need to pass `--include-crds`. I have verified that the flag applies not only to charts v2 and the "new" `/crds` directory as well as the old, deprecated, `"helm.sh/hook": crd-install` from charts v1.

Note that rendering CRDs every time as we do in kapp controller have many caveats, as the [Helm team explained here](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you), which made them decouple CRDs from the rendering and just apply them on install. In any case, this is something we can look into whenever/if we work on proper [helm installation support](https://github.com/vmware-tanzu/carvel-kapp-controller/issues/99). 

**b) Include two binaries, the latest V2 helm  and a new V3 version**

We could technically have both binaries and choose one or the other based on the `apiVersion: v1` in the `Chart.yaml` file. This will keep the current level of Helm v2 support without relying on Helm V3's fallback.

**My 2 cents**

Taking into account that 1) Helm v2 and its associated chart spec is not maintained anymore, 2) Most of the community seem to have upgraded their charts already and 3) Helm V3 has good enough chart v1 spec fallback support I see no apparent reason why we could not just bump the version of Helm (option a).

The only reason I can think of (assuming that a change like this will be part of a versioned release) in favor to maintaining two binaries is to make sure that we do not break `vendir` implementation, although I do not know if this is even a problem just yet.   

Thoughts?

Thanks!

**Comment by vibhas** [comment] 2021-04-06 19:47
Hi @migmartri, thanks for offering your help! We were just about to reply to your previous comment stating that it would be great to get your contribution on this issue and if you could share how you might want to approach it so that the team can offer their thoughts before you spend the effort to implement it.

Looks like you are already on top of it! :-) I am going to tag few folks so that they can provide their thoughts on the approach. @cppforlife @ewrenn8 @danielhelfand @aaronshurley

**Closed as completed** 2021-04-19 18:31 UTC
Labels: enhancement
