### ISSUE TITLE
`kctrl package repository release` Should Allow Control of Image Tags

### ISSUE THREAD

**Issue by nebhale** [carvel-dev/kapp-controller#1639] opened 2024-11-13 18:47 UTC
**Describe the problem/challenge you have**
Currently, there is no way to control the image tags for created and published package repository imgpkg bundles.  This prevents the creation of a package repository with a version that includes any build metadata, e.g. `0.0.1+git.c9cc39a`

**Describe the solution you'd like**
The `kctrl package repository release` command should gain a `--tag` flag that is the equivalent of the `kctrl package release` command's `--tag` flag.

**Anything else you would like to add:**
[Slack](https://kubernetes.slack.com/archives/CH8KCCKA5/p1731518888544399)

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by mamachanko** [comment] 2024-11-18 06:59
@nebhale @praveenrewar This might be a duplicate of https://github.com/carvel-dev/kapp-controller/issues/1409

**Comment by nebhale** [comment] 2024-11-18 14:51
They are related in the sense that they're both triggered by the same thing (the inability to use build metadata) but in detail they're different.  My specific ask is for a flag to create parity between `kctrl package release` and `kctrl package repository release` and the other requests an automated mapping.

**Comment by devacts** [comment] 2024-12-19 09:33
@nebhale Currently, the version provided by the user in the args is the added as image tag (or the unix timestamp if version is empty)
If I understand correctly, with this change, the user will be able to override that version tag by providing a user specific tag.
The image tag applied would take precedence in following order:

1. --tag
2. --version
3. unix time stamp

**Comment by nebhale** [comment] 2024-12-19 18:10
@devanshuVmware Do you have to hand, the precedence for how the `kctrl package publish` works?  I thought that `--version` wasn't included in that precedence hierarchy.

**Comment by devacts** [comment] 2024-12-20 07:50
@nebhale Currently, the tag that is applied to the imgpkg bundle image is:
if `--version` flag is provided, apply it
else, add the unix timestamp as tag

with the introduction of `--tag` flag, I understand, its value should take precedence as tag, even if the user provides a value for the `--version` flag
if the `--tag` is not provided but `--version` is , then `--version` value will be used as tag,
if neither are provided, the default tag would be unix timestamp

**Comment by nebhale** [comment] 2024-12-20 15:38
Yeah, I have no strong opinion other than consistency with the package behavior 😀. Looks like that's the path you're heading down.

**Closed as completed** 2024-12-25 05:57 UTC
Labels: enhancement, carvel-triage, carvel-accepted, cli, priority/important-longterm

**Comment by nebhale** [comment] 2024-12-30 18:03
Validated this works as expected.  Is there a regular release cadence for the project that I should expect this to fall into?

**Comment by devacts** [comment] 2024-12-31 09:07
> Validated this works as expected. Is there a regular release cadence for the project that I should expect this to fall into?

Thanks for validating it @nebhale !
The next release for KC is planned towards end of Jan. However, we can make an early release if you need it sooner.

**Comment by nebhale** [comment] 2025-01-02 15:27
It’d be helpful to have it released earlier (we’d start using the new feature the first day it’s available) but at the same time, this isn’t make-or-break for us, so don’t kill yourself trying to get it out the door.

**Comment by nebhale** [comment] 2025-01-10 13:09
Saw the release yesterday and have already integrated it.  Thanks for the quick turn around!
