### ISSUE TITLE
Unable to Create Package Repository in Local Environment using Carvel Docs

### ISSUE THREAD

**Issue by kartiklunkad26** [carvel-dev/kapp-controller#728] opened 2022-06-08 22:45 UTC
**What steps did you take:**
I was following the steps outlined in [Adding a Package Repository](https://carvel.dev/kapp-controller/docs/v0.37.0/packaging-tutorial/#adding-a-packagerepository), with setting up a local registry and kind cluster using this recent [PR](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/develop/examples/local-kind-environment/scripts/kind-with-registry.sh#L4-L11)

**What happened:**
Getting the below error when creating the Package Repository. 
```
Fetching image:
    Get "https://127.0.0.1:5000/v2/": dial tcp 127.0.0.1:5000: connect: connection refused; Get "http://127.0.0.1:5000/v2/": dial tcp 127.0.0.1:5000: connect: connection refused
)
```
**What did you expect:**
I expected the Package Repository to be set-up successfully, or further instructions in the Carvel docs in case I don't have the right set-up to do so.  

**Anything else you would like to add:**

**Environment:**

- kapp Controller verison: 
 `kapp-controller.carvel.dev/version: v0.32.0`
- Kubernetes version (use `kubectl version`)
Client version: v1.23
Server version: v1.21

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joe-kimmel-vmw** [comment] 2022-06-15 16:45
Hi @kartiklunkad26 !  - thanks for filing!

You're right - the instructions provided were for the (late) katacoda platform which is no longer available. I would expect them to still work on most linux machines but they aren't general. 

On a mac, if you run `ipconfig getifaddr en0` can you confirm that you get something that looks like an IP address (e.g. I get 192.168.1.107). 

The trick here is that `127.0.0.1` always refers to the most localest of localhosts so when you run that from within a pod, in a node, in a k8s cluster, in a VM,  your network request won't escape the VM's network out to your development machine. 

The fundamental move is to ensure that the variable `REPO_HOST` has a value that can be resolved from within your k8s cluster. So in this case, we just take advantage of the VM's network being able to see our development machine's IP address.   Other options include using a fully external repo such as dockerhub or github-container-registry and then putting the corresponding url into the REPO_HOST variable.  

We can update the tutorial, but that contents is actually in a separate repo.

**Comment by joe-kimmel-vmw** [comment] 2022-06-15 16:47
@kartiklunkad26  how do you think we should update the docs ?  The local registry made sense when it was possible to have a fully reproducible katacoda environment, but now do you think it makes more sense to tell the docs-consumer to use a dockerhub account?

**Comment by neil-hickey** [comment] 2023-02-22 19:01
Closing this out for now as done.

**Closed as completed by neil-hickey** 2023-02-22 19:01 UTC
Labels: documentation
