### ISSUE TITLE
Support layering of package repositories

### ISSUE THREAD

**Issue by danielhelfand** [carvel-dev/kapp-controller#428] opened 2021-11-19 19:19 UTC
**Describe the problem/challenge you have**

For a user of kapp-controller, the possibility exists to create two PackageRepositories which may contain a Package with the same name. It could be the case that these are the exact same Package, but it could also be that the names are the same but there are differences between the Packages.

Currently, due to kapp-controller's use of `kapp` as its method for creating Packages, kapp-controller will fail to create a Package with the same name as another in the same namespace. Since PackageRepositories are often created around software products that can be independent of one another (e.g. Tanzu Application Platform and Tanzu Community Edition), it makes sense for this duplication to occur where both products want to both make the same Package available (e.g. cert-manager). 

kapp-controller should support a way of dealing with these conflicts to provide a better user experience for package consumers working with multiple repositories. 

**Describe the solution you'd like**

There currently exist some workarounds for this issue:
* Coming up with a unique name for a conflicting Package (e.g. maybe including the product name in the package name)
* Keep same package name but use slightly different version. The challenge with this workaround is that a PackageMetadata resource can only be owned by one PackageRepository.

It's not immediately clear what the long term way to address this problem is, but some ideas that have been considered are:
* Having kapp-controller create Packages without using `kapp`. Maybe using the k8s client to develop a custom experience for kapp-controller around handling conflicts.
* Supporting a way to define precedence and which Package kapp-controller should prefer. An example of this is a PackageRepo for product 1 has a cert-manager Pacakge that should be preferred over PackageRepo for product 2's cert-manager Package. What this experience would look like and how a user could configure this have yet to be determined.
* Could kapp-controller more gracefully handle the case of conflicts instead of showing a PackageRepository as failing to reconcile in the case where a conflict exists.
* Is there anything that could be directly implemented in `kapp` to address this issue?

**Anything else you would like to add:**

Are there any additional cases to consider beyond two Packages conflicting within the same namespace?

One question to still be answered is if kapp-controller will still create all Packages except the conflicting Package in the case of a conflict.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joe-kimmel-vmw** [comment] 2021-12-08 21:43
just a note for my own book-keeping: private notes doc for this issue is here https://docs.google.com/document/d/1mHrhIVM42_NNpML-ZtAzdbgMhtAL5xIlxIY5oMhi7ik/edit

**Comment by joe-kimmel-vmw** [comment] 2021-12-09 18:30
@cppforlife To me the most interesting question is "when to resolve" -- Some of these paths would only ever have one package of same-name on the system, so they have to resolve at package creation time. 

Other strategies would allow creation of packages of "same name" and then have strategies for helping the user specify which one they want. 

To me that's a pretty big divide in experience and would be helpful to have direction on that question first.

**Comment by joe-kimmel-vmw** [comment] 2021-12-09 19:00
re. first strategy there's still multiple options around "first one in wins" vs. "most recent one wins", whether or not you provide a cli-flag or config priority flag so that the user can still select which one wins, etc.

re the second strategy of allowing multiple packages of same name,  i think discussing with @vibhas briefly it's helpful to outline vaguely one way that could work:   we can add a disambiguating "long name" that includes some info about the pkgr/profile/source as kc sees it at pkg creation time (whether that's through a kapp invocation or through the k8s client),  and then map "short names" to "long names" such that if there's only 1 short name in the map everything works exactly as before (fully backwards compat) but user is required to disambiguate if there's 2+ short names.

**Comment by voor** [comment] 2021-12-09 19:06
When you say "name" do you mean `refName` or do you mean the merging of the `refName` and `version` to create the Package's actual `name`?

**Comment by joe-kimmel-vmw** [comment] 2021-12-09 19:09
sorry @voor  i think this is what i get trying to be vague and hand-wavy, huh? 😄 
>When you say "name" do you mean refName or do you mean the merging of the refName and version to create the Package's actual name?

honestly what i mean is "I haven't thought through everything yet."  

 If you see some potential pitfalls/problems please feel free to call the out,  but the big question to me at the moment is whether we want to sort this out at package creation time,  or at package install time.

**Comment by voor** [comment] 2021-12-09 19:17
I think it'd be interesting if we had a refName collision and *not* a version collision, if you could technically have things play nicely in an unintentional way.  So cert-manager from Tanzu Community Edition collides with cert-manager from Tanzu Application Platform (assume for this exercise that both use the refName `cert-manager.tanzu.vmware.com`):

cert-manager from TCE is currently `1.6.1` and would be `cert-manager.tanzu.vmware.com.1.6.1`
cert-manager from TAP is currently `1.5.3+tap.1` and would be `cert-manager.tanzu.vmware.com.1.5.3+tap.1`

The result should be that `versionSelection` _might_ work as intended and upgrade you to 1.6.1.  That might have been the thought process for the `+tap.1` in the cert-manager version. :thinking:

**Comment by vrabbi** [comment] 2021-12-09 19:54
I think that the idea of a long name makes alot of sense.
I think it should be before the version and should be - seperated from the package name.
so for the example above the names would be:

TAP REPO
Short name: cert-manager.tanzu.vmware.com.1.5.3+tap.1
Long name: cert-manager.tanzu.vmware.com-\<pkgr name\>.1.5.3+tap.1

TCE REPO
Short name: cert-manager.tanzu.vmware.com.1.6.1
Long name: cert-manager.tanzu.vmware.com-\<pkgr name\>.1.6.1

**Comment by vrabbi** [comment] 2021-12-09 19:54
This would also partially help users understand in general which repo a package comes from which is currently a problem

**Comment by joe-kimmel-vmw** [comment] 2021-12-09 20:05
some notes from chat w/ DK:

user consuming packages should only ever see 1 package. 
Users who are providing packages are the ones who should be adding additional metadata. 

favored solution is that if a user has to explicitly set a numeric priority (z-stack / z-index in graphical "layering" system).  b/c it's fully deterministic (no ordering effects).   in Tanzu products generally same name will actually be the exact same product.  However a layering would allow a "user override" so if a user wanted to patch something they could add their own package with same-name but higher priority (though they could also just y'know make a new name and choose that name).,   but this kind of layering supports replacing, generally.

**Comment by voor** [comment] 2021-12-09 20:26
> layering would allow a "user override"
> but this kind of layering supports replacing, generally.

So like some kind of _overlay_ passthrough for the Package Repository. :innocent: https://github.com/vmware-tanzu/carvel-kapp-controller/issues/397

**Comment by jorgemoralespou** [comment] 2021-12-10 10:53
Despite this being a problem that needs a solution, to me, there's a fundamental problem if we have same package (e.g. cert-manager.tanzu.vmware.com) coming from 2 different repositories with different, potentially conflicting, implementations. Even if the problem of naming in 2 repositories is solved, how can we guarantee that the implementations of both packages coming from different sources (e.g. cert-manager.tanzu.vmware.com.1.5.3+tap.1 and cert-manager.tanzu.vmware.com.1.6.1) are compatible and that one package could be easily upgraded to the other one? 

It's not only about conflicting names, but also about conflicting functionality and API for those packages.

**Comment by cppforlife** [comment] 2021-12-10 18:17
> how can we guarantee that the implementations of both packages coming from different sources (e.g. cert-manager.tanzu.vmware.com.1.5.3+tap.1 and cert-manager.tanzu.vmware.com.1.6.1) are compatible and that one package could be easily upgraded to the other one?

this problem is not really related to layering of repositories though -- it's just a generic problem that package author (aka owner of cert-manager.tanzu.vmware.com name) should worry about. whoever decides to "steal" somebody elses name (rare) they should abide by their versioning/conventions/etc. this is not something we want to enforce in any way. (similar thing is CRD group names/versions)

**Comment by jorgemoralespou** [comment] 2021-12-10 18:21
I agree totally. That's why I think that all these packages should be published in the same repository, and hence wouldn't be the source of the problem herein described.
But since we fear this will happen, as currently does in Tanzu, I can confirm that packages are not compatible already. TCE provides OpenSource version of packages and TKG provides commercial, with same name and incompatible implementations. And it's all coming from the same company. 🤷

**Comment by cppforlife** [comment] 2021-12-10 18:29
> with same name and incompatible implementations

different names! one has "community" in the package names, and one doesnt. i was very specific with folks on that building it because those 2 sets of packages are different in configuration and implementation (at least at this point).

**Comment by jorgemoralespou** [comment] 2021-12-10 19:01
My bad. I guess TAP OSS also follows this convention.

**Comment by joe-kimmel-vmw** [comment] 2021-12-10 21:49
I made an interactive demo for the layering proposal -  i thought github would natively render static html but anyway you can visit it via a tool such as : https://htmlpreview.github.io/?https://raw.githubusercontent.com/vmware-tanzu/carvel-kapp-controller/5df913d9d105dff60031e81d9c62d8222c76a25a/examples/packaging-with-repo/issue-428-demo.html

**Comment by joe-kimmel-vmw** [comment] 2021-12-11 00:11
@cppforlife -- through playing with the little 'prototype'/demo  i realized - one of your stated arguments in favor of this z-index style layering is that it would be fully deterministic,  but that's only true for packages with different priority values--  e.g. if we set the default to `10` and multiple packages install at the default value,  then there's still a race or undefined behavior.

**Comment by cppforlife** [comment] 2021-12-13 14:24
> if we set the default to 10 and multiple packages install at the default value, then there's still a race or undefined behavior.

that's right, we need to determine what we want to do with this... should we error for example?

**Comment by joe-kimmel-vmw** [comment] 2022-04-26 17:42
noticing that this issue hasn't been updated in a long time:   most recent proposed solution(s) are:


We propose a solution in two parts: 
(1) make it “just work” as often as possible; 
(2) provide a manual mechanism (used by package/repo authors) for resolving ambiguous situations. From a design perspective we want to ensure alignment around which scenarios should “just work” while also confirming that the effort required for manual resolution is appropriate.

“Make it just work” : kapp-controller does not emit errors if two packages have the same name+version and also are identical. In cases where the name+version collide but package contents are not deemed identical, the reconciliation of one of the repositories would fail (just like today). 

How do we define “identical?”
However, possibilities include:
- 100% identical package spec after the repository has been fetched and templated.
- Package spec matches for certain fields (which fields?)
- Package fetch locations are identical (allows for substantial/arbitrary divergence in templating and configuration)
- Note the notion of ‘identical’ is mushy if the package & repository authors are using tags instead of hashes, but this isn’t new behavior.


“Ambiguity Resolution” two parts:

1. Revision Counter: add mechanism to allow package authors to increment revision for subsequent releases of the same name+version (e.g metadata typo fixes, deprecation warnings). In cases of name+version collision kapp-controller will prefer the highest revision and ignore all lower revisions. 
Implementation:

Proposed: Annotation, e.g.  `[packaging.carvel.dev/revision](http://packaging.carvel.dev/revision): "X"`
Alternative: Spec-level “revision: <int>” to the Package and PackageMetadata CRD (Note: this option would require a special case in the proposed “100% identical package spec” above)

2. Exclusion List: Kapp-controller supports a PKGR level “exclusion” list for both Packages and PackageMetadatas: 
 If reconciliation fails because we find identically named & versioned packages in the package repos, but those packages fail the “identical” match above,  then the cluster admin needs to modify one of the pkgr yamls to add an "exclusion list" and add the identical package to that list

**Comment by joe-kimmel-vmw** [comment] 2022-06-30 18:06
I think this was closed by #657

**Closed as completed by joe-kimmel-vmw** 2022-06-30 18:06 UTC
Labels: enhancement, carvel-accepted
